### ISSUE TITLE
rrdjig fails with Floating Exception upon encountering an RRA with start == stop

### ISSUE THREAD

**Issue by ZNikke** [oetiker/rrdtool-rrdjig#1]
Upon rejig:ing a bunch of RRD:s with historical data we encountered a few RRDs which probably are a bit weird, but rrdtool dump/restore processes them fine.

rrdjig however triggers a Floating Exception.

After a bit of debugging I discovered that this happens when rrdjig does [RRDs::fetch](https://github.com/oetiker/rrdtool-rrdjig/blob/89e92e945ebcd83389f985b0827ebd57f2598ef1/rrdjig.pl#L126) with the same time as --start and --end.

My workaround is to avoid this like so:

```
my ($start,$step,$names,$array);
if($t->{start} != $t->{end}) {
    ($start,$step,$names,$array) = RRDs::fetch(
        $src,$cf,'--resolution',$t->{step},
        '--start',$t->{start},'--end',$t->{end}
        );
}
```

I suspect that RRDs::fetch probably shouldn't crash on start==end, but until that's fixed in the distributions others might find this workaround useful.

**Comment by oetiker** [comment]
Maybe 6621212 helps ... note that in rrdtool 1.5 create has learned to use an existing rrd to pre-populate.
