### ISSUE TITLE
Error: "Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196."

### ISSUE THREAD

**Issue by depasseg** [oetiker/rrdtool-rrdjig#2]
I'm getting the following errors repeatedly scrolling when trying to run rrdjig.

Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.
Use of uninitialized value in numeric le (<=) at ./rrdjig.pl line 196.

**Comment by oetiker** [comment]
please use rrdtool 1.6, its create function contains all the functionality from rrdjig AND more

**Comment by depasseg** [comment]
Thank you.  I didn't realize apt was so far behind.
